# Generated by Django 4.2.7 on 2025-11-19 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_user_region_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetassignment',
            name='assignment_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_records', to='assets.region'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assignment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_records', to='assets.assetstatus'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_records', to='assets.user'),
        ),
        migrations.AlterModelTable(
            name='assetassignment',
            table='asset_assignments',
        ),
    ]
